const AddPositionLocators = {
    positionTitle: '#formEditPosition_title',
    selectBranchDropdown: 'input[placeholder="Select branch ..."]',
    branchName: '.nvc-sl-popover-item-name.ng-binding',
    savePositionInGeneralDetailsButton: '.fa.fa-check',
    generalDetailsSubTab: 'a[ui-sref="edit_position.general"]',
    recruitingProcessSubTab: 'a[ui-sref="edit_position.recruiting_steps"]',
    addNewStepButton: 'button[ng-click="createStep()"]',
    stepNameField: '.ng-pristine.ng-untouched.ng-invalid',
    selectStepTypeDropdown: 'input[placeholder="Select step..."]',
    stepTypeName: '.nvc-sl-popover-item-name.ng-binding',
    addStepInGroupButton: 'button[ng-click="addStepInGroup($event)"]',
    stepInGroupNameField: 'input[class="form-control ng-pristine ng-untouched ng-invalid ng-invalid-required"]',
    addNewTagDropdown:'span[class="zz-select__text ellipsis ng-binding"] span[class="ng-scope"]',
    tagName:'.zz-option.ng-scope.ng-isolate-scope',
    selectCustomerDropdown: 'input[placeholder="Select customer..."]',
    customerName:'.nvc-sl-popover-item-name.ng-binding',
    selectPositionDropdown:'input[placeholder="Select position..."]',
    positionsName:'.nvc-sl-popover-item-name.ng-binding',
    selectEmailTemplateDropdown:'div[nvd-select="email_templates"] input[placeholder="Select template..."]',
    emailTemplateName:'.nvc-sl-popover-item-name.ng-binding',
    SMSCheckBox:'label[class="ml10 checkbox_icon"]',
    selectSMSTemplateDropdown:'div[nvd-select="sms_templates"] input[placeholder="Select template..."]',
    SMSTemplateName:'.nvc-sl-popover-item-name.ng-binding',
    templateName:'.nvc-sl-popover-item-name.ng-binding',
    savePositionInProcessButton: 'button[title="Save changes"]',
    currentPositionStatusDropdown: 'span[ng-bind="currentPositionStatus.name"]',
    statusName:'span[ng-bind="::status.name"]',
    duplicateButton:'button[class="position-stat-btn"]',
    goToNewPosition:'[ng-click="goToNewPosition()"]',
    genericLoadTemplateButton:'div[id="generic"] div[class="zz-select btn-group margin-horiz-05 dropdown"] button[type="button"]',
    personalLoadTemplateButton:'#personal_evaluation',
    loadTemplateName:'.zz-option.ng-binding.ng-scope',
    loadTemplateOKButton:'button[type="submit"]',
    Email_SMSRadioButton:'[class="ellipsis ng-binding"]',
    sendingTypeManualRadioButton:'//label[normalize-space()="Manual"]',
    sendingTypeAutomaticRadioButton:'//label[normalize-space()="Automatic"]',
    onlineSurveySelectTemplate:'input[placeholder="Select template..."]',
    settingsSurveyTab: 'li[class="ng-isolate-scope active"]',
    formsSurveyTab: 'li[class="ng-isolate-scope"]',
    formTitleField: '[ng-model="step.form_title"]',
    formDescriptionField: '[ng-model="step.form_description"]',
    XButton: '[aria-hidden="true"]',

    
    successSaveMessage:'div[role="alert"][type="success"]',
}
export default AddPositionLocators